# 开发环境配置
app:
  prefix: '/api'
  port: 8080
  logger:
    # 项目日志存储路径，相对路径（相对本项目根目录）或绝对路径
    dir: '../logs'
# 数据库配置
db:
  mysql:
    host: 'xxxxxxxxx'
    username: 'xxxx'
    password: 'xxxxx'
    database: 'xxx'
    port: 3306
    charset: 'utf8mb4'
    logger: 'advanced-console'
    # 设置日志的级别
    logging: ["error"]
    multipleStatements: true
    dropSchema: false
    synchronize: true
    supportBigNumbers: true
    bigNumberStrings: true

# redis 配置
redis:
  host: 'xxxxxxx'
  port: 6379
  password: xxxxxxxx
  db: 9
  keyPrefix: 'nest:'
  namespace: 'default'

# redis 订阅分布配置
redisSubscriber:
  host: 'xxxxxx'
  port: 6379
  password: xxxxxxxx
  namespace: 'subscriber'

# rabbmitMq 配置
rabbmitMq:
  host: 'xxxxxx'
  port: 5672
  username: 'xxxxxx'
  password: 'xxxxxx'
  vhost: 'xxxxxx'