# 开发环境配置
app:
  prefix: '/api'
  port: 8080
  logger:
    # 项目日志存储路径，相对路径（相对本项目根目录）或绝对路径
    dir: '../logs'
  # 文件相关, 开发环境
  file:
    # location 文件上传后存储目录，相对路径（相对本项目根目录）或绝对路径
    location: '../upload'
    # 文件服务器地址，请自行定义可访问地址
    domain: 'http://localhost:8081'
# 数据库配置
db:
  mysql:
    host: 'localhost'
    username: 'root'
    password: 'root'
    database: 'kapok'
    port: 3306
    charset: 'utf8mb4'
    logger: 'advanced-console'
    logging: true
    multipleStatements: true
    dropSchema: false
    synchronize: true
    supportBigNumbers: true
    bigNumberStrings: true

# redis 配置
redis:
  host: 'localhost'
  port: 6379
  db: 0
  keyPrefix: 'nest:'

# redis 订阅分布配置
redisSubscriber:
  host: 'xxxxxx'
  port: 6379
  password: xxxxxxxx
  namespace: 'subscriber'

# rabbmitMq 配置
rabbmitMq:
  host: 'xxxxxx'
  port: 5672
  username: 'xxxxxx'
  password: 'xxxxxx'
  vhost: 'xxxxxx'